### ISSUE TITLE
Template not fetching sensor values

### ISSUE THREAD

**Issue by gsaudade99** [blind-oracle/zabbix-sensors#12]
Hello,

 I'm having a problem with getting the values from the sensors of my linux server.The problems seems to be recurrent as I followed [this](https://www.zabbix.com/forum/zabbix-help/421657-zabbix-sensors-not-executed) thread in zabbix forum. 
 
 Could you look into this and give some feedback?
 
 Kind regards,

**Comment by blind-oracle** [comment]
It's hard to say, but for sure this is wrong:
```
/etc/zabbix/zabbix_agentd.d/sensors.conf contains this line:

UserParameter=lmsensors.discover[*],/etc/zabbix/scripts/sensors.py $1
```

Please see this file https://github.com/blind-oracle/zabbix-sensors/blob/master/sensors.conf

**Comment by gsaudade99** [comment]
After looking into the server logs I got this:

```
[root@zabbix-server ~]# tail -f /var/log/zabbix/zabbix_server.log 
1. Failed: SyntaxError: invalid json (at offset 1)
    at [anon] (duktape.c:37568) internal
    at parse () native strict preventsyield
    at [anon] (function:1) preventsyield
  1707:20240327:144326.301 discovery rule "srv-prox1-dc:sensors.discovery.voltage" became not supported: Preprocessing failed for: sh: 1: /etc/zabbix/scripts/sensors.py: Permission denied
```

I managed to fix it doing:
```
chmod +x /etc/zabbix/scripts/sensors.conf
chown zabbix:zabbix /etc/zabbix/scripts/sensors.py
systemctl restart zabbix-agent2 
```
