### ISSUE TITLE
Problems and questions

### ISSUE THREAD

**Issue by zakkya** [blind-oracle/zabbix-sensors#2]
Hello, thanks for the work you did even it doesn't work for me lol.

First, I want to know if this tool could gives data, makes graphics, or not at all and only send warnings.

Second, the Item key isn't supported, I'm on 4.2 version.

Third, tell me if i'm wrong : 
- I installed lm-sensors on **my client**
- I added the files sensors.conf & discover-sensors.py on **my client**
- I imported the .xml
- I added the Template_Sensors to my client in the configuration

Thank you for reply !
Aurèle

**Comment by blind-oracle** [comment]
> First, I want to know if this tool could gives data, makes graphics, or not at all and only send warnings.
Which tool? There's a template with discovery rules, graphs you can see in 'Latest data'

> Third, tell me if i'm wrong
The procedure looks good.

> Second, the Item key isn't supported, I'm on 4.2 version.
It should give you some explaination on why it's not supported. It's hard to debug without logs etc.
