### ISSUE TITLE
Cannot evaluate expression: Invalid macro '{$SENSORS_HIGH}' value on Zabbix 4.0.1

### ISSUE THREAD

**Issue by VChernenkoRT** [blind-oracle/zabbix-sensors#3]
Everything seems fine despite of triggers not working in Z401 with "Invalid macro '{$SENSORS_HIGH}' value", "Invalid macro '{$SENSORS_CRIT}' value". How to fix this behavior?

**Comment by blind-oracle** [comment]
Hi. It's strange, the {$SENSORS_CRIT} macro is defined in the template and should work. It worked for me on 4.4 and now works on 5.0

You can try upgrading Zabbix (maybe there's some bug in 4.0.1) or replacing macros with some values in a trigger.

**Comment by VChernenkoRT** [comment]
as I see in discover-sensors.py there is no sensor type "SENSORS" (lines 27-30), therefore discover-sensors.py cannot output {$SENSORS_HIGH} and {$SENSORS_CRIT} data which exists in template triggers.

**Comment by VChernenkoRT** [comment]
aaand theres no {$SENSORS_HIGH} and {$SENSORS_CRIT} overriding macros/values in template_sensors.xml

**Comment by blind-oracle** [comment]
These are template-level macros, they're defined in the template and have some defaults.
They're used if you don't override them on the host level.

**Comment by blind-oracle** [comment]
> aaand theres no {$SENSORS_HIGH} and {$SENSORS_CRIT} overriding macros/values in template_sensors.xml

Yes I guess I forgot to add them. They're there in my own template, but not in github for whatever reason. I'll fix it, sorry.
