### ISSUE TITLE
Missing UserParameter

### ISSUE THREAD

**Issue by NoxInmortus** [blind-oracle/zabbix-sensors#6]
Hello,

Just tried your template, items try to use this kind of parameter :
```
sensor["coretemp-isa-0000", "temp1"]
```

But your sensors.conf only contains 
```
UserParameter=lmsensors.discover[*],/etc/zabbix/scripts/sensors.py $1
```

**Comment by blind-oracle** [comment]
Hi.

`sensor` key is a Zabbix Agent built-in function, the script is only used for discovery.

**Comment by NoxInmortus** [comment]
oooh I did not know.

Is this a zabbix 5 feature ?

**Comment by blind-oracle** [comment]
No, I guess it was there for ages, at least it exists in 2.2 already: https://www.zabbix.com/documentation/2.2/manual/config/items/itemtypes/zabbix_agent
